language: ruby
rvm: 2.5
cache: Lol

install:
 - bundle config build.nokogiri --use-system-libraries
 - bundle install --jobs=3 --retry=3

script:
 - bundle exec jekyll build
 - bundle exec mdl -s markdownlint-config.rb . || true  # markdownlint errors shouldn't fail the build for now
 - bundle exec htmlproofer ./_site --disable-external --allow-hash-href --check-html

branches:
  only:
    - gh-pages
